### ISSUE TITLE
Request for Ubuntu image with patched OBS pre-installed

### ISSUE THREAD

**Issue by Linkaan** [Costor/nvmpi-obs-streamFX#3]
Hello,

I found this project after digging in the OBS documentation for the last couple of days. It seems very promising and I'm trying to set this up for my friend who wants a simple and cheap solution for streaming using OBS.

I have tried to get this to work based on my very little knowledge of OBS and the Nvidia Jetson, however I don't seem to be able to get a working installation without OBS crashing with a segfault when pressing "start streaming" or "start recording"

To make this project easier for people to use it would be very helpful to provide an image with OBS preinstalled with support for the NVMPI encoder.

Atleast some instructions on how to create an image would be nice. For starters, how do I upgrade to Ubuntu 20.04 on my Jetson? The L4T based images provided by Nvidia are Ubuntu 18.04.

**Comment by Costor** [comment]
Hi Linkaan,
what you want to do is what I wanted to do, i.e. use the nano as an obs streaming engine - so I see your point.
Unfortunately I'm unable to maintain this project, and I'm definitely unable to provide images.

It's a pity that Nvidia doesn't provide better support for their jetsons for normal users, e.g. provide up-to-date ubuntu-images, and a decent integration of their nvmpi codec, e.g. a Chromium with nvmpi support compiled in etc.

I did an update to ubuntu 20.04 myself following an description I found somewhere on the web but as far as I remember the upgrade was far from trouble free. But the descriptions will have been updated in the meantime so it might be worth to give it a try.

Sorry I can't do more.

**Comment by Linkaan** [comment]
Hello Costor,

thanks for the quick response. I understand that it's not possible for you to maintain this and I appreciate the work you have put into this. 

Regarding Ubuntu 20.04 I did find this image which I will try to use as a starting point: https://github.com/Qengineering/Jetson-Nano-Ubuntu-20-image

I read that you are currently using this setup for your own use, could you briefly tell me about the setup you are using so I can try it myself (e.g do you use a USB webcam to stream or is it a camera connected via the MIPI CSI-2 connector and what settings do you use in OBS)?

Perhaps there would be someone interested in collaborating on this project. I found this github repo which seems to use the hardware encoder on the nvidia jetson: https://github.com/steveseguin/raspberry_ninja/blob/main/nvidia_jetson/README.md
